[tool.poetry]
name = "rag-self-query"
version = "0.0.1"
description = ""
authors = ["foo bar <foo@bar.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
openai = "^0.28.1"
elasticsearch = "^8.10.0"
sentence-transformers = "^2.2.2"
jq = "^1.6.0"
tiktoken = "^0.5.1"

[tool.langserve]
export_module = "rag_self_query"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
